package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/sqlc-dev/plugin-sdk-go/codegen"
	plugin "github.com/sqlc-dev/plugin-sdk-go/plugin"
)

type pluginOptions struct {
	FileName    string              `json:"file_name"`
	QueryRename map[string]string   `json:"query_rename"`
	DropParams  map[string][]string `json:"drop_params"`
}

type queryMeta struct {
	Name string
}

func main() {
	codegen.Run(func(_ context.Context, req *plugin.GenerateRequest) (*plugin.GenerateResponse, error) {
		opts := loadOptions(req.GetPluginOptions())

		var b strings.Builder
		b.WriteString("// Generated by sqlc-dts plugin\n\n")

		queries := make([]queryMeta, 0, len(req.GetQueries()))
		for _, q := range req.GetQueries() {
			name := q.GetName()
			if alias, ok := opts.QueryRename[name]; ok && strings.TrimSpace(alias) != "" {
				name = strings.TrimSpace(alias)
			}

			params := q.GetParams()
			params = applyDropParams(name, params, opts.DropParams)
			writeReqType(&b, name, params)
			b.WriteString("\n")
			writeResType(&b, name, q)
			b.WriteString("\n")

			queries = append(queries, queryMeta{Name: name})
		}

		writeAPITypes(&b, queries)

		fileName := strings.TrimSpace(opts.FileName)
		if fileName == "" {
			fileName = "api-types.d.ts"
		}

		return &plugin.GenerateResponse{Files: []*plugin.File{{
			Name:     fileName,
			Contents: []byte(b.String()),
		}}}, nil
	})
}

func loadOptions(raw []byte) pluginOptions {
	opts := pluginOptions{
		QueryRename: map[string]string{},
		DropParams:  map[string][]string{},
	}
	if len(raw) == 0 {
		return opts
	}
	_ = json.Unmarshal(raw, &opts)
	if opts.QueryRename == nil {
		opts.QueryRename = map[string]string{}
	}
	if opts.DropParams == nil {
		opts.DropParams = map[string][]string{}
	}
	return opts
}

func writeReqType(b *strings.Builder, queryName string, params []*plugin.Parameter) {
	fmt.Fprintf(b, "export type %sReq = {\n", queryName)
	for i, p := range params {
		col := p.GetColumn()
		name := strings.TrimSpace(col.GetName())
		if name == "" {
			name = fmt.Sprintf("arg%d", i+1)
		}
		op := ""
		if !col.GetNotNull() {
			op = "?"
		}
		typ := mapParamType(col)
		fmt.Fprintf(b, "  %s%s: %s;\n", name, op, typ)
	}
	b.WriteString("}\n")
}

func writeResType(b *strings.Builder, queryName string, q *plugin.Query) {
	cols := q.GetColumns()
	many := isManyQuery(q.GetCmd())

	if len(cols) == 0 {
		if many {
			fmt.Fprintf(b, "export type %sRes = (any)[]\n", queryName)
		} else {
			fmt.Fprintf(b, "export type %sRes = (any)\n", queryName)
		}
		return
	}

	if len(cols) == 1 {
		t := mapColumnType(cols[0])
		if many {
			fmt.Fprintf(b, "export type %sRes = (%s)[]\n", queryName, t)
		} else {
			fmt.Fprintf(b, "export type %sRes = (%s)\n", queryName, t)
		}
		return
	}

	fmt.Fprintf(b, "export type %sRes = {\n", queryName)
	for i, col := range cols {
		name := strings.TrimSpace(col.GetName())
		if name == "" {
			name = fmt.Sprintf("column_%d", i+1)
		}
		op := ""
		if !col.GetNotNull() {
			op = "?"
		}
		typ := mapColumnType(col)
		fmt.Fprintf(b, "  %s%s: %s;\n", name, op, typ)
	}
	if many {
		b.WriteString("}[]\n")
	} else {
		b.WriteString("}\n")
	}
}

func writeAPITypes(b *strings.Builder, queries []queryMeta) {
	b.WriteString("export type apiTypes = {\n")
	for i, q := range queries {
		end := ";"
		if i == len(queries)-1 {
			end = ""
		}
		fmt.Fprintf(b, "  \"%s\": [%sReq, %sRes]%s\n", q.Name, q.Name, q.Name, end)
	}
	b.WriteString("}\n")
}

func mapColumnType(col *plugin.Column) string {
	return mapType(col, false)
}

func mapParamType(col *plugin.Column) string {
	return mapType(col, true)
}

func mapType(col *plugin.Column, isParam bool) string {
	if col == nil {
		return "any"
	}

	base := mapBaseType(col, isParam)
	dims := int(col.GetArrayDims())
	if dims == 0 && col.GetIsArray() {
		dims = 1
	}
	for i := 0; i < dims; i++ {
		base += "[]"
	}
	return base
}

func mapBaseType(col *plugin.Column, isParam bool) string {
	_ = isParam
	t := normalizeTypeName(col.GetType().GetName())
	if t == "" || t == "any" {
		return "any"
	}

	switch t {
	case "bool", "boolean":
		return "boolean"
	case "smallint", "int2", "integer", "int4", "serial", "serial4", "smallserial", "real", "float4", "float8", "double precision", "numeric", "decimal":
		return "number"
	case "bigint", "int8":
		return "number"
	case "bigserial", "serial8", "int":
		return "number"
	case "json", "jsonb":
		return "Record<string, any>"
	case "uuid", "text", "varchar", "bpchar", "char", "character varying", "citext", "timestamptz", "timestamp", "date", "time", "timetz", "point":
		return "string"
	default:
		if strings.Contains(t, "char") || strings.Contains(t, "text") || strings.Contains(t, "time") {
			return "string"
		}
		if strings.Contains(t, "json") {
			return "Record<string, any>"
		}
		if strings.Contains(t, "int") || strings.Contains(t, "numeric") || strings.Contains(t, "float") || strings.Contains(t, "double") {
			if col.GetIsFuncCall() {
				return "number"
			}
			return "any"
		}
		return "any"
	}
}

func normalizeTypeName(name string) string {
	t := strings.ToLower(strings.TrimSpace(name))
	if t == "" {
		return t
	}
	if i := strings.LastIndex(t, "."); i >= 0 && i < len(t)-1 {
		t = t[i+1:]
	}
	return t
}

func isManyQuery(cmd string) bool {
	return strings.Contains(strings.ToLower(cmd), "many")
}

func applyDropParams(queryName string, params []*plugin.Parameter, drop map[string][]string) []*plugin.Parameter {
	if len(drop) == 0 {
		return params
	}
	names := drop[queryName]
	if len(names) == 0 {
		return params
	}
	set := make(map[string]struct{}, len(names))
	for _, n := range names {
		n = strings.TrimSpace(n)
		if n != "" {
			set[n] = struct{}{}
		}
	}
	if len(set) == 0 {
		return params
	}
	out := make([]*plugin.Parameter, 0, len(params))
	for _, p := range params {
		if _, ok := set[p.GetColumn().GetName()]; ok {
			continue
		}
		out = append(out, p)
	}
	return out
}
